#!/bin/sh /etc/rc.common
# AREDN Probe Responder init script

START=95
STOP=10

USE_PROCD=1

PROG=/usr/bin/probe-responder

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "probe-responder"
}
