name: Build and Release

on:
  push:
    branches:
      - main
      - development
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        target:
          - arch: ath79
            subtarget: generic
          - arch: x86
            subtarget: 64
          - arch: ipq40xx
            subtarget: generic

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SDK URL
        id: sdk
        run: |
          if [ "${{ matrix.target.arch }}" = "ipq40xx" ]; then
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/${{ matrix.target.arch }}/${{ matrix.target.subtarget }}/openwrt-sdk-23.05.3-${{ matrix.target.arch }}-${{ matrix.target.subtarget }}_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          else
            echo "sdk_url=https://downloads.openwrt.org/releases/23.05.3/targets/${{ matrix.target.arch }}/${{ matrix.target.subtarget }}/openwrt-sdk-23.05.3-${{ matrix.target.arch }}-${{ matrix.target.subtarget }}_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_OUTPUT
          fi

      - name: Download and extract SDK
        run: |
          wget --progress=bar:force "${{ steps.sdk.outputs.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz
          mv openwrt-sdk-* sdk

      - name: Copy package to SDK
        run: |
          mkdir -p sdk/package/aredn-probe-responder
          cp -r src Makefile files sdk/package/aredn-probe-responder/

      - name: Build package
        run: |
          cd sdk
          make defconfig
          make package/aredn-probe-responder/compile V=s -j$(nproc)

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          find sdk/bin/packages -name "aredn-probe-responder*.ipk" -exec cp {} artifacts/ \;
          ls -lh artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-${{ matrix.target.arch }}-${{ matrix.target.subtarget }}
          path: artifacts/*.ipk
          retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release-artifacts/**/*.ipk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
